/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -v -c RouteControlsAdaptor -a route_controls_adp route_ctl.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "route_controls_adp.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class RouteControlsAdaptor
 */

RouteControlsAdaptor::RouteControlsAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

RouteControlsAdaptor::~RouteControlsAdaptor()
{
    // destructor
}

double RouteControlsAdaptor::WptGet(double &lon)
{
    // handle method call sn.ornap.navd.route.WptGet
    //return static_cast<YourObjectType *>(parent())->WptGet(lon);

    double lat;
    QMetaObject::invokeMethod(parent(), "WptGet", Q_ARG(double &, lat), Q_ARG(double &, lon));
    return lat;
}

void RouteControlsAdaptor::WptSet(double lat, double lon)
{
    // handle method call sn.ornap.navd.route.WptSet
    QMetaObject::invokeMethod(parent(), "WptSet", Q_ARG(double, lat), Q_ARG(double, lon));
}

