/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -v -c RouteManagerAdaptor -a route_manager_adp route_mgr.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ROUTE_MANAGER_ADP_H_1449765977
#define ROUTE_MANAGER_ADP_H_1449765977

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface sn.ornap.navd.routemanager
 */
class RouteManagerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "sn.ornap.navd.routemanager")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"sn.ornap.navd.routemanager\">\n"
"    <method name=\"StartNav\">\n"
"      <arg direction=\"in\" type=\"d\" name=\"lat\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"lon\"/>\n"
"      <arg direction=\"out\" type=\"o\" name=\"routePath\"/>\n"
"    </method>\n"
"    <method name=\"StopNav\">\n"
"      <arg direction=\"in\" type=\"o\" name=\"route_path\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    RouteManagerAdaptor(QObject *parent);
    virtual ~RouteManagerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QDBusObjectPath StartNav(double lat, double lon);
    void StopNav(const QDBusObjectPath &route_path);
Q_SIGNALS: // SIGNALS
};

#endif
