/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -v -c RouteControlsAdaptor -a route_controls_adp route_ctl.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ROUTE_CONTROLS_ADP_H_1449765988
#define ROUTE_CONTROLS_ADP_H_1449765988

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface sn.ornap.navd.route
 */
class RouteControlsAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "sn.ornap.navd.route")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"sn.ornap.navd.route\">\n"
"    <method name=\"WptGet\">\n"
"      <arg direction=\"out\" type=\"d\" name=\"lat\"/>\n"
"      <arg direction=\"out\" type=\"d\" name=\"lon\"/>\n"
"    </method>\n"
"    <method name=\"WptSet\">\n"
"      <arg direction=\"in\" type=\"d\" name=\"lat\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"lon\"/>\n"
"    </method>\n"
"    <signal name=\"Data\">\n"
"      <arg type=\"d\" name=\"deltaLat\"/>\n"
"      <arg type=\"d\" name=\"deltaLon\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    RouteControlsAdaptor(QObject *parent);
    virtual ~RouteControlsAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    double WptGet(double &lon);
    void WptSet(double lat, double lon);
Q_SIGNALS: // SIGNALS
    void Data(double deltaLat, double deltaLon);
};

#endif
